theme: jekyll-theme-slate

title: ATQAM Workshop
description: 1st Workshop on Aesthetic and Technical Quality Assessment of Multimedia
subheading1: In conjunction with ACM Multimedia 2020
subheading2: 12-16 October 2020 â€¢ Seattle, US

show_downloads: false
